#version: "3.7"

networks:
  blogapp-network:
  
services:
  blogapp-sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "U4bT^3)ewQ"
        ACCEPT_EULA: "Y"
    network_mode: "host"