networks:
  blogapp-network:
  
services:
  sql-server-database:
    container_name: sql-server-database
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "U4bT^3)ewQ"
        ACCEPT_EULA: "Y"
    networks:
      - blogapp-network