services:
  sql-server-database:
    container_name: sql-server-database
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "U4bT^3)ewQ"
        ACCEPT_EULA: "Y"
    network_mode: "host"
